### ISSUE TITLE
Vagrant plugin install fails on Windows behind proxy

### ISSUE THREAD

**Issue by ojacques** [devops-dojo/the-app#17]
When trying to install Vagrant plugins as specified in the [install doc](), one can get an error:
```C:\>vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostsupdater (> 0)'
```

**Comment by ojacques** [comment]
Let's try this: 
`export http_proxy=http://your_web_proxy:port/` and try again. 
Alternatively, making this change permanent can be done under control panel/Advanced System Settings/Environment variables

**Comment by saf01** [comment]
Hello Ojacques.  Thank you for the suggestion.  I was assuming that the Windows command (cmd) prompt / app picked up the proxy information but it does not.  Using the commands below after starting the command prompt as Administrator resolved the problem.

Thanks!

Commands used:
C:\>set http_proxy=http://proxy.xxxx.xxxx.net:8080
C:\>set http_proxy=https://proxy.xxxx.xxxx.net:8080

C:\>vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Fetching: vagrant-hostsupdater-1.0.2.gem (100%)
Installed the plugin 'vagrant-hostsupdater (1.0.2)'!

C:\>

**Comment by ojacques** [comment]
Thanks @saf01 - closing this issue!
