### ISSUE TITLE
Error when microservices register with monitoring d.c.b.a.s.SpringBootAdminRegistrator

### ISSUE THREAD

**Issue by ojacques** [devops-dojo/the-app#19]
Getting errors in the log of navigation, cart and product microservices:

Failed to register application as [id=null, url=http://app-server-node-4:18090, name=navigation-microservice] at spring-boot-admin (http://monitoring.microservice.io:8080//api/applications): I/O error on POST request for "http://monitoring.microservice.io:8080/api/applications":Connection refused; nested exception is java.net.ConnectException: Connection refused

**Comment by ojacques** [comment]
The apps try to register to "Spring Boot Admin".
But [SpringBootAdmin](https://github.com/codecentric/spring-boot-admin) is not installed
https://github.com/devops-dojo/the-app/blob/master/vagrant/provision/monitoringserver.yml

**Comment by ojacques** [comment]
Let's remove the integration with Springbootadmin altogether.
In node 3 and 4, see `/var/log/cart`,  `/var/log/product`, `/var/log/navigation`

**Comment by chavezom** [comment]
Disabled in the following files:

https://github.com/devops-dojo/the-app/blob/master/microservice/service/cart/src/main/resources/application.properties
https://github.com/devops-dojo/the-app/blob/master/microservice/service/cart/src/main/resources/application.properties
https://github.com/devops-dojo/the-app/blob/master/microservice/service/navigation/src/main/resources/application.properties

**Comment by chavezom** [comment]
Logs are clean now
