### ISSUE TITLE
Sign In functionality not working

### ISSUE THREAD

**Issue by sprreddy** [devops-dojo/the-app#84]
Step 1 : Logout from the shop if already logged in.
Step 2 : Click the "Sign in" link in the top right corner of the screen
Step 3 : Do not enter any user id / password and click "Sign In"

Expected Result : The user should be signed in if the correct credentials are provided or an error should be shown for the user to correct his/her details.

Actual Result : The screen becomes unresponsive.

**Comment by ojacques** [comment]
Good for the exercise! Will not fix.
Thanks.
