### ISSUE TITLE
Microservices site lacking "You may like" suggested products 

### ISSUE THREAD

**Issue by wzolandz** [devops-dojo/the-app#87]
Steps to reproduce:

1) Navigate to the microservices site.

The "You may Like" area is not showing.
![](https://cloud.githubusercontent.com/assets/25772731/22988569/2fe9fdb2-f378-11e6-922f-df6d12239cc2.png)

Monolithic page for comparison:
![](https://cloud.githubusercontent.com/assets/25772731/22988596/494d2c3e-f378-11e6-8cc9-6fd97020a615.png)

**Comment by ojacques** [comment]
Good for the exercise! Will not fix.
Thanks.
