### ISSUE TITLE
No item prices listed on microservices site pages

### ISSUE THREAD

**Issue by wzolandz** [devops-dojo/the-app#88]
Steps to reproduce.

1. Navigate to microservices test app page.
2. View either Home/Handy/Tablet pages.

No prices will be listed on the devices as shown in below screenshot.
![](https://cloud.githubusercontent.com/assets/25772731/22987930/faf459ba-f375-11e6-9804-96e99b7ef8af.png)

**Comment by ojacques** [comment]
Good for the exercise! Will not fix.
Thanks.
